// cards.js
export const cards = [
    "Katt",
    "Hund",
    "Fågel",
    "Häst",
    "Fisk",
    "Ballong",
    "Mobiltelefon",
    "Ryggsäck",
    "Glass",
    "Hammare",
    "Panda",
    "Lejon",
    "Älg",
    "Ekorre",
    "Delfin",
    "Noshörning",
    "Känguru",
    "Sköldpadda",
    "Bläckfisk",
    "Grävling",
    "Räv",
    "Uggla",
    "Papegoja",
    "Säl",
    "Myra",
    "Får",
    "Hummer",
    "Giraff",
    "Krabba",
    "Paraply",
    "Kikare",
    "Tandborste",
    "Fjärrkontroll",
    "Kamera",
    "Gosedjur",
    "Pennvässare",
    "Förstoringsglas",
    "Trädgårdsslang",
    "Rullskridskor",
    "Skruvmejsel",
    "Hårborste",
    "Kaffekopp",
    "Tändsticka",
    "Soptunna",
    "Tuggummi",
    "Ficklampa",
    "Stege",
    "Cykelhjälm",
    "Sax",
    "Mikrofon",
    "Vattenflaska",
    "Visselpipa",
    "Diskborste",
    // ... lägg till resten sen,
    // ... Fundera på kategorier
    // ... Fundera på val av kategorier när man startar

];